### ISSUE TITLE
Cannot install tinycudann

### ISSUE THREAD

**Issue by 1ssb** [kylesargent/zeronvs#24]
$ python tiny-cuda-nn/bindings/torch/setup.py 
tiny-cuda-nn/bindings/torch/setup.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_version
Traceback (most recent call last):
  File "tiny-cuda-nn/bindings/torch/setup.py", line 8, in <module>
    import torch
  File "/home/users/user/anaconda3/envs/zeronvs/lib/python3.8/site-packages/torch/__init__.py", line 237, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/users/user/anaconda3/envs/zeronvs/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so: undefined symbol: ncclCommRegister

**Comment by shuichuanqhs** [comment]
Hello, I have encountered the same problem. Have you solved it？
